# Introducción

Con motivo de presentar la metodología del trabajo territorial que se adelanta en el marco del proyecto de inversión 1901 `Incremento de la disponibilidad de medicamentos Monopolio del Estado para los pacientes en Colombia Nacional Código BPIN 2020011000020` y puesto que uno de los ejes centrales para garantizar la disponibilidad de los medicamentos monopolio del estado (MME) en el territorio nacional, *recae en el manejo que le den a los mismos cada una de las entidades encargada en su respectivo departamento*, en este documento se resumen los resultados de la recolección de información concerniente en los Fondos Rotatorios de Estupefacientes (FRE) de todo el país.

Este proyecto se diseñó con la finalidad de cumplir con dos objetivos en específico, el primer objetivo es fortalecer el proceso de abastecimiento de medicamentos monopolio del Estado, identificando fuentes de información asociada a la prescripción, dispensación y uso de medicamentos monopolio del Estado, con énfasis en el recetario oficial y generar informes de análisis de los datos reportados por los Fondos Rotatorios de Estupefacientes (FRE) para el manejo de medicamentos monopolio del Estado que permitan un seguimiento eficaz y oportuno.

El segundo objetivo busca mejorar la cantidad y calidad de la prescripción de medicamentos monopolio del Estado realizando visitas, reuniones, mesas de trabajo e intercambios de experiencias con los FRE, médicos prescriptores, químicos farmacéuticos, enfermeros y otros profesionales de la salud del territorio nacional. Esto como base para construir herramientas y piezas con información veraz acerca de MME, de manera comprensiva y precisa para diferentes públicos (pacientes, prestadores, otros) con el fin de mejorar conductas y hábitos del estado de salud.

A continuación, se describe toda la información obtenida de los FRE a nivel nacional descrito en dos componentes. El primero, acerca de los procesos de adquisición, venta, distribución, seguimiento, recepción, consolidación y archivo de recetarios oficiales. Y el segundo, relacionado a las proyecciones de compra, recepción técnica, almacenamiento e inventario de los medicamentos monopolio del estado y sus respectivos anexos reglamentados en las Resolución 1478 de 2006 [@MSPS1478-2006] y Resolución 1479 de 2006 [@MSPS1479-2006].

Este proceso de inmersión territorial se desarrolló entre los meses de abril y septiembre de 2021. Los funcionarios de los FRE, atendieron el llamado del Fondo Nacional de Estupefacientes (FNE) con la mejor disposición, brindando información relevante para el proyecto de inversión 1901 y comentando las diferentes vicisitudes que suceden en el territorio. El desarrollo de las reuniones se llevó a cabo de manera exitosa, de forma fluida y cordial.

