---
output:
  pdf_document: default
  html_document: default
---

# Recetarios oficiales

```{r configuracion1-L102, include=FALSE}
require(tidyverse); theme_set(theme_bw())
require(plotly)
require(sf)
require(ggrepel)
require(ggsflabel)
require(patchwork)
require(scatterpie)
require(vistime)

fig_path <- file.path('..', '..', 'figures')

barButtons <- c("zoomIn2d", "zoomOut2d", "lasso2d", "pan2d", 
                                    "select2d", "drawclosedpath", "autoScale2d", "zoom2", 
                                    "toggleSpikelines", "hoverCompareCartesian", "hoverClosestCartesian", 
                                    "resetScale2d")
```

\maxdeadcycles=1000

## Existencia de recetarios


```{r existenciasRecetarios, echo=FALSE, fig.cap='N.° de existencias de recetarios en el FRE', fig.width=8, fig.height=6, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, '027_existenciaRecetarios_1.rds')) + 
  labs(title = NULL)
```

```{r existenciasRecetarios2, echo=FALSE, fig.cap='N.° de recetarios circulantes en el departamento', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, '028_existenciaRecetarios_2.rds')) + 
  labs(title = NULL)
```

```{r existenciaRecetarios3, echo=FALSE, fig.cap='Duración de existencia de recetarios en el FRE', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, '029_existenciaRecetarios_3.rds')) + 
  labs(title = NULL)
```

```{r existenciaRecetarios4, echo=FALSE, fig.cap='N.° de prescripciones por recetario', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, '030_existenciaRecetarios_4.rds')) + 
  labs(title = NULL)
```

## Costos de recetarios

```{r costoRecetario, echo=FALSE, fig.cap='Comparativo de costo vs precio de recetarios por departamento', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="90%"}
readRDS(file.path(fig_path, '031_costoRecetario.rds')) + 
  labs(title = NULL)
```

```{r comparativoDepartamentos, echo=FALSE, warning=FALSE, fig.cap='Comparativo de costo vs precio y márgen de beneficio', fig.width=8, fig.height=6, fig.topcaption=TRUE, out.width="90%"}
readRDS(file.path(fig_path, '032_comparativoDepartamentos.rds')) + 
  labs(title = NULL)
```

```{r comparativoDepartamentos2, echo=FALSE, warning=FALSE, fig.cap='Comparativo de costo vs precio y márgen de beneficio (2)', fig.width=8, fig.height=4, fig.topcaption=TRUE}
readRDS(file.path(fig_path, '033_comparativoDepartamentos1.rds')) + 
  labs(title = NULL)
```

```{r PVTA-Recetarios, echo=FALSE, warning=FALSE, fig.cap='Precio de venta de recetario por prescripción', fig.width=9, fig.height=5, fig.topcaption=TRUE, out.width="90%"}
readRDS(file.path(fig_path, '034_PVTA_recetarios_prescripcion.rds')) + 
  labs(title = NULL)
```

## Tiempos de adquisición de recetarios

```{r modalidadAdquisicion, echo=FALSE, warning=FALSE, fig.cap='Modalidad de selección para contratos de adquisición de recetarios', fig.width=7, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, '035_modalidadAdquisicion.rds')) + 
  labs(title = NULL)
```

```{r tiempoDemoraAdquisicion, echo=FALSE, warning=FALSE, fig.cap='Tiempo de demora para adquisición de recetarios', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, '036_demoraRecetario.rds')) + 
  labs(title = NULL)
```

```{r BD-diligBDRecet, echo=FALSE, warning=FALSE, fig.cap='Proporción de FRE que diligencian campos en BD de venta de recetarios', fig.width=7, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "041_BD_diligBDRecet.rds")) + 
  labs(title = NULL)
```

```{r SeguimientoUsoRecetarios, echo=FALSE, warning=FALSE, fig.cap='Actividades realizadas por el FRE para el seguimiento del uso de recetarios', fig.width=8, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "043_SeguimientoUsoRecetarios.rds")) + 
  labs(title = NULL)
```

## Tiempos de despacho de recetarios
```{r MedidasSeguridadRec, echo=FALSE, warning=FALSE, fig.cap='Medidas de seguridad en los recetarios', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="90%"}
readRDS(file.path(fig_path, "045_MedidasSeguridadRec.rds")) + 
  labs(title = NULL)
```

```{r ComparativoCostosRec, echo=FALSE, warning=FALSE, fig.cap='Comparativo de márgen de ganancia de recetarios', fig.width=10, fig.height=5, fig.topcaption=TRUE, message=FALSE, out.width="90%"}
readRDS(file.path(fig_path, "046_ComparativoCostosRecetarios.rds")) + 
  labs(title = NULL)
```

```{r ReciboRecetariosInstituciones, echo=FALSE, warning=FALSE, fig.cap='Recibo de recetarios de instituciones inscritas', fig.width=6, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "047_ReciboRecetarios.rds")) + 
  labs(title = NULL)
```

```{r TiempoRecepcionRecOficiales, echo=FALSE, warning=FALSE, fig.cap='Tiempo de recepción de recetarios oficiales desde IPS', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "048_ReciboRecetariosIPS.rds")) + 
  labs(title = NULL)
```

```{r TiempoArchivoRecetariosOficiales, echo=FALSE, warning=FALSE, fig.cap='Tiempo de archivo de los recetarios oficiales en los FRE', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "049_DuracionRecetFRE.rds")) + 
  labs(title = NULL)
```

```{r MedidasSeguridad-Almacenamiento, echo=FALSE, warning=FALSE, fig.cap='Medidas de seguridad en almacenamiento de recetarios', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "050_MedidasSeguridadAlmac.rds")) + 
  labs(title = NULL)
```

```{r InformacionHerramiento-VentasRecetarios, echo=FALSE, warning=FALSE, fig.cap='Proporción de FRE que diligencian en campo de ventas de recetarios', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "051_InformacionHerramienta.rds")) + 
  labs(title = NULL)
```

## Recetario Oficial Electrónico

```{r FREImplementacionROE, echo=FALSE, warning=FALSE, fig.cap='Opinión sobre la implementación del Recetario Oficial Electrónico (ROE)', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "042_FRE_implementacionROE.rds")) + 
  labs(title = NULL)
```

```{r TiempoVentaInstituciones, echo=FALSE, warning=FALSE, fig.cap='Tiempo de demora en la venta de recetarios oficiales a clientes', fig.width=8, fig.height=6, fig.topcaption=TRUE, out.width="90%"}
readRDS(file.path(fig_path, "132_TiempoVentaInstituciones.rds")) + 
  labs(title = NULL)
```
