---
output:
  pdf_document: default
  html_document: default
---

# Reporte de informes


```{r configuracion1-L104, include=FALSE}
require(tidyverse); theme_set(theme_bw())
require(plotly)
require(sf)
require(ggrepel)
require(ggsflabel)
require(patchwork)
require(scatterpie)
require(vistime)

fig_path <- file.path('..', '..', 'figures')

barButtons <- c("zoomIn2d", "zoomOut2d", "lasso2d", "pan2d", 
                                    "select2d", "drawclosedpath", "autoScale2d", "zoom2", 
                                    "toggleSpikelines", "hoverCompareCartesian", "hoverClosestCartesian", 
                                    "resetScale2d")
```

\maxdeadcycles=1000

```{r HerramientasDiligA1, echo=FALSE, warning=FALSE, fig.cap='Herramientas en el diligenciamiento del Anexo 1 de la Resolución 1479 de 2006', fig.width=7, fig.height=5, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "073_HerramientaConsol.rds")) + 
  labs(title = NULL)
```


```{r ControlesVentasFRE, echo=FALSE, warning=FALSE, fig.cap='Controles en las ventas directas a pacientes', fig.width=8, fig.height=6, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "120_ControlesVentasFRE.rds")) + 
  labs(title = NULL)
```
```{r TiemposConsolidacionA1, echo=FALSE, warning=FALSE, fig.cap='Tiempo en la consolidación del Anexo 1 de la Resolución 1479 de 2006', fig.width=8, fig.height=6, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "121_TiemposConsolidacionA1.rds")) + 
  labs(title = NULL)
```
```{r RecepcionA13, echo=FALSE, warning=FALSE, fig.cap='Medio para consolidación de Anexo 13 de la Resolución 1478 de 2006', fig.width=8, fig.height=6, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "122_RecepcionA13.rds")) + 
  labs(title = NULL)
```
```{r ArchivoInformesFRE, echo=FALSE, warning=FALSE, fig.cap='Tiempo de archivo de Anexo 13 de la Resolución 1478 de 2006', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "123_ArchivoInformesFRE.rds")) + 
  labs(title = NULL)
```
```{r SeguimientoEnvioInformes, echo=FALSE, warning=FALSE, fig.cap='Mecanismo de seguimiento de instituciones de envío de informes', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "125_SeguimientoEnvioInformes.rds")) + 
  labs(title = NULL)
```
```{r IncumplimientoEnvioInformes, echo=FALSE, warning=FALSE, fig.cap='Medidas por incumplimiento de envío de informes', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "126_IncumplimientoEnvioInformes.rds")) + 
  labs(title = NULL)
```

## Seguridad de la información
```{r GarantiaInformacion, echo=FALSE, warning=FALSE, fig.cap='Medidas para garantizar la seguridad de la información', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "127_GarantiaInformacion.rds")) + 
  labs(title = NULL)
```
```{r InformInscritos, echo=FALSE, warning=FALSE, fig.cap='Proporción de FRE que cuenta con base de dato con información de inscritos', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "128_InformInscritos.rds")) + 
  labs(title = NULL)
```
```{r InformPacientes, echo=FALSE, warning=FALSE, fig.cap='Proporción de FRE que cuenta con una base de datos con información de pacientes a los que se les dispensa MME', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "129_InformPacientes.rds")) + 
  labs(title = NULL)
```

La pregunta a la cual se refiere la Figura \@ref(fig:InstitucionesAdicionales) se trata de las instituciones que realizan ventas de MME a pacientes, no la entiendo muy bien!!!!.


```{r InstitucionesAdicionales, echo=FALSE, warning=FALSE, fig.cap='Existencia de otras instituciones que realizan ventas a instituciones a MME', fig.width=6, fig.height=4, fig.topcaption=TRUE, out.width="85%"}
readRDS(file.path(fig_path, "131_InstitucionesAdicionales.rds")) + 
  labs(title = NULL)
```