# Créditos {-}

### Grupo Desarrollador {-}

```{r include=FALSE}
  bloqueContactos <-
    function(Nombre = 'Nombre',
             Cargo = 'Cargo',
             ruta = "./credit_figures/person_icon.jpg",
             altura = 15, # rem
             ancho = '50%',
             img_alt = "person_icon_logo") {
      #
      tags <- htmltools::tags
      principal <- glue::glue("width: {ancho}; 
                              flex-direction: row; 
                              display: flex; 
                              height: {altura}rem;")
      
      tags$div(
        tags$div(tags$img(src = ruta, alt = img_alt, 
                          style = 'border-radius: 50%', height='80%'),
                 style = "display: flex; width: 30%;"),
        tags$div(
          tags$div(tags$strong(Nombre, display='block'),
                   style = "display:flex; justify-content:center; align-items:center; height: 45%; padding: 4rem;"),
          tags$div(tags$i(Cargo, display='block'),
                   style = "display:flex; justify-content:center; align-items:center; height: 45%; padding: 4rem;"),
          style = paste('display: flex', 
                        'flex-direction: column', 
                        'justify-content: space-around',
                        'align-content: space-around',
                        ' width: 70%',
                        sep = ';')
        ),
        style = principal
      )
    }
credits_fig <- file.path('.', 'credit_figures')
```


<hr>
**Coordinación**
<br>
```{r creditos1, echo=FALSE, warning=FALSE}
tag1 <- htmltools::tags

tag1$div(
  bloqueContactos('Diego Alejandro Socha Cuitiva', 'Dirección',
                  './credit_figures/diego.jpg'),
  bloqueContactos('Hillary Andrea Gómez Guerra', 'Coordinación de proyecto',
                  './credit_figures/hillary.jfif'),
  style = paste('width: 100%',
                'display: flex',
                'align-items: flex-start',
                'flex-wrap: wrap',
                'justify-content: space-around',
                sep = ';')
)
```

<hr>
**Apoyo**
<br>
```{r, echo=FALSE, warning=FALSE}
tag1$div(
  bloqueContactos('Carlos Andres Acosta Pinto', 'Apoyo operativo',
                  './credit_figures/carlos.jfif'),
  bloqueContactos('Daniela del Pilar Carvajal Latorre', 'Apoyo operativo',
                  './credit_figures/daniela.jfif'),
  style = paste('width: 100%',
                'display: flex',
                'align-items: flex-start',
                'flex-wrap: wrap',
                'justify-content: space-around',
                sep = ';')
)
```

<hr>
**Realización de encuestas**
<br>
```{r, Realización de encuestas, echo=FALSE, warning=FALSE}
tag1$div(
  bloqueContactos('Jhonathan Felipe Venegas Parra', 'Profesional de equipo técnico territorial',
                  './credit_figures/jonathan.jfif', altura = 15),
  bloqueContactos('Nicolas Alexander Cadena Ayala', 'Profesional de equipo técnico territorial',
                  './credit_figures/nicolas.jfif', altura = 15),
  bloqueContactos('Carlos Guillermo Leal Jimenez', 'Profesional de equipo técnico territorial',
                  altura = 15),
  bloqueContactos('Wilder Estiben Meneses Garavito', 'Profesional de equipo técnico territorial',
                  './credit_figures/estiben.jfif', altura = 15),
  style = paste('width: 100%',
                'height: 35 rem',
                'display: flex',
                'align-items: flex-start',
                'flex-wrap: wrap',
                'justify-content: space-around',
                'align-content: space-around',
                sep = ';')
)
```

<hr>
**Estadística**
<br>
```{r, Estadistica, echo=FALSE, warning=FALSE}
tag1$div(
  bloqueContactos('Daniel Sebastián Parra González', 'Estadístico', 
                  './credit_figures/daniel.png'),
  style = paste('width: 100%',
                'display: flex',
                'align-items: flex-start',
                'flex-wrap: wrap',
                'justify-content: space-around',
                sep = ';')
)
```

<hr>
**Diagramación**
<br>
```{r, Diagramacion, echo=FALSE, warning=FALSE}
tag1$div(
  bloqueContactos('Julieth Fernanda Contreras Garcia', 'Comunicadora'),
  bloqueContactos('Fabian Oswaldo Millán Ibarra', 'Comunicadora'),
  style = paste('width: 100%',
                'display: flex',
                'align-items: flex-start',
                'flex-wrap: wrap',
                'justify-content: space-around',
                sep = ';')
)
```